### ISSUE TITLE
@kensanata packages on the Emacswiki

### ISSUE THREAD

**Issue by tarsius** [emacsmirror/.github#3]
Hey @kensanata!

Thanks for moving those of your packages that are available from Melpa from the Emacswiki to Github. The Emacsmirror imports more packages from the Emacswiki than Melpa and there are still a few packages that you wrote that are only available from the Emacswiki. Could you please consider moving these to Github too and/or tell me which of these should be considered unmaintained and/or no longer useful. I would move those to the Emacsattic and no longer update them.

- [x] bidi
- [x] **dom** now known as **doom**
- [x] erobot
- [x] eval-sexp-in-comments
- [x] flashmaker
- [x] **htmlr**
- [x] idle-scroll
- [x] kdic
- [x] loops
- [x] mu
- [x] really-simple-wiki
- [x] sql-transform
- [x] textmenu
- [x] toolbox
- [x] unparen
- [x] wiki
- [x] wiki-remote

This is a follow up to https://github.com/melpa/melpa/issues/2342#issuecomment-344839302.

**Comment by kensanata** [comment]
Uuuugh, so many? So much abandoned code?

I’ll take a look. 😓

**Comment by tarsius** [comment]
Friendly ping!

**Comment by kensanata** [comment]
https://github.com/kensanata/emacs-bidi

**Comment by kensanata** [comment]
https://github.com/kensanata/kdic also takes care for flashmaker

**Comment by kensanata** [comment]
https://github.com/kensanata/idle-scroll

**Comment by kensanata** [comment]
https://github.com/kensanata/loops

**Comment by kensanata** [comment]
An unexpected gift: mu.el already exists! https://github.com/kensanata/mu

**Comment by tarsius** [comment]
Thanks!

I will update the Emacsmirror in one go once you are all done (or tell me that you won't tackle the remaining packages anytime soon).

**Comment by kensanata** [comment]
https://github.com/kensanata/wiki – uuuugh, major pain!

**Comment by tarsius** [comment]
I have updated the Emacsmirror up to this point. Thanks!

I also found two more packages:

* `dom` aka `doom`

  Someone else took over as maintainer and put the page [here](https://github.com/toroidal-code/dom.el). Meanwhile another `dom` was added to Emacs. I tried to [get upstream to change the name](https://github.com/toroidal-code/dom.el/issues/2). When that failed I did that myself and [put the fork](https://github.com/emacsorphanage/doom) on the Emacsorphanage. Could we move that repository to your account instead?

* `htmlr`

  Someone else took over as maintainer and left it on the Emacswiki. It does not look like that person is still active.

**Comment by tarsius** [comment]
Should https://www.emacswiki.org/emacs/WikiRemote also be added to `wiki`?

**Comment by tarsius** [comment]
I am afraid I found some more: https://github.com/emacsjanitors/http-emacs.

**Comment by kensanata** [comment]
Hm, I don't recognize that code. I fear that was other people building on wiki.el or something like that.

**Comment by kensanata** [comment]
Also, in your original todo list, you can check *wiki remote*.
I just tried *textmenu* and it doesn't seem to work with my current Emacs. There's no point having it in the repo, right?

**Comment by kensanata** [comment]
https://github.com/kensanata/unparen

**Comment by tarsius** [comment]
> Hm, I don't recognize that code. I fear that was other people building on wiki.el or something like that.

Okay.

> I just tried textmenu and it doesn't seem to work with my current Emacs. There's no point having it in the repo, right?

I've moved it to the attic.

**Comment by kensanata** [comment]
https://github.com/kensanata/toolbox

**Comment by tarsius** [comment]
I found another one https://github.com/emacsattic/eval-sexp-in-comments. That's actually something I would like to be able to do! In this case you will also have to cleanup the header and specify the license. Maybe it would be better to advice `eval-last-sexp` instead of providing a new command.

**Comment by kensanata** [comment]
Unrelated to all of the above, I just adopted https://github.com/kensanata/rcirc-late-fix because I couldn't find it anywhere.

**Comment by tarsius** [comment]
You might also want to add this to Melpa, but it will only be accepted if you make some effort to contact the previous maintainer and make some commitment to actually maintain the package.

**Comment by kensanata** [comment]
Better not, then. No promises...

**Comment by kensanata** [comment]
I forked https://github.com/kensanata/doom

**Comment by kensanata** [comment]
https://github.com/kensanata/eval-sexp-in-comments

**Comment by kensanata** [comment]
https://github.com/kensanata/1000-words

**Comment by kensanata** [comment]
https://github.com/kensanata/really-simple-wiki

**Comment by tarsius** [comment]
Do you intend to do this for the remaining three packages too?

**Comment by kensanata** [comment]
https://github.com/kensanata/htmlr

**Comment by kensanata** [comment]
https://github.com/kensanata/sql-transform

**Comment by kensanata** [comment]
https://github.com/kensanata/erobot

Wohooo!

**Comment by tarsius** [comment]
Thanks a lot!
