### ISSUE TITLE
Adding pinentry

### ISSUE THREAD

**Issue by DamienCassou** [emacsmirror/.github#4]
The pinentry.el package was builtin but has been removed in Emacs 26. This package is on Elpa: https://elpa.gnu.org/packages/pinentry.html. I see in https://emacsmirror.net/stats/compare.html#orge9bad0e that pinentry already is a special case. Can you please add pinentry to the Emacs mirror?

/cc @NicolasPetton

**Comment by tarsius** [comment]
It's always interesting to run the "update built-in packages" code. Lets see how much bit rot has accumulated since the previous pre-release 😉

**Comment by tarsius** [comment]
Pretty harmless this time around. Some sanity checks reported differences when they actually just failed to normalize the order of two values before comparison.

**Comment by tarsius** [comment]
Mirroring https://github.com/ueno/pinentry-el now.

**Comment by DamienCassou** [comment]
The version on @ueno's repository seems to be quite outdated compared to the [version removed from the emacs tree](https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/net/pinentry.el?h=b3f4a3a5ae). The [version in elpa](https://git.savannah.gnu.org/cgit/emacs/elpa.git/tree/packages/pinentry/pinentry.el) is also outdated. In the newest version (removed from Emacs), the first line of code is

```emacs
(eval-when-compile (require 'cl-lib))
```

/cc @ueno. Where should pinentry be taken from?

**Comment by tarsius** [comment]
It would probably be best to transplant the history from Emacs onto the upstream history (using `git filter-branch` and such).

**Comment by NicolasPetton** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> It would probably be best to transplant the history from Emacs onto
> the upstream history (using `git filter-branch` and such).

We're applying git commits from emacs.git that touched pinentry.el, and
I'll do the same in elpa.git.

BTW, will the package from elpa.gnu.org be mirrored, or only the GitHub
repo?

**Comment by DamienCassou** [comment]
I created a PR applying all patches from Emacs tree to upstream: https://github.com/ueno/pinentry-el/pull/3

**Comment by tarsius** [comment]
> BTW, will the package from elpa.gnu.org be mirrored, or only the GitHub repo?

I tend to mirror the upstream (here github) repository because the history in Elpa tends to be incomplete due to the use of `git subtree --squash`. But if upstream lags behind (and I notice it), then I usually switch to mirroring from Elpa.

**Comment by NicolasPetton** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> I tend to mirror the upstream (here github) repository because the
> history in Elpa tends to be incomplete due to the use of `git subtree
> --squash`.

This package in ELPA is just a directory, so its maintenance will
quickly become a burden if there is a separate GitHub repository.
