### ISSUE TITLE
Sync package after history rewrite

### ISSUE THREAD

**Issue by kostafey** [emacsmirror/.github#6]
I've made some bad commits to https://github.com/kostafey/ejc-sql package and then join them by `git rebase`. But emacsmirror version https://github.com/emacsmirror/ejc-sql already synced with previous repo state. So, looks like there are no more sync operations after that.
How it's possible to fix this problem?

**Comment by tarsius** [comment]
Normally that results in a modified submodule. I don't check for those after every automated update but should do so about twice a month. For some reason the Github API did not report that this repository was modified so no pull was attempted.

I am now running a full update that ignores API data and just pulls every repository to see if there are other such packages.

**Comment by tarsius** [comment]
A dozen other packages were also affected. I will have to figure out how exactly Github is being less helpful than it could be here. (Or maybe it is a bug in my code but I doubt it.)

Anyway I've updated your package now.
