### ISSUE TITLE
scad-mode out of sync?

### ISSUE THREAD

**Issue by kevinboulain** [emacsmirror/.github#7]
Hi there,

Based on https://emacsmirror.net/#adding-new-packages every package from Melpa should be synced to their respective repository.

From what I can see, Melpa's scad-mode has been updated in April (Melpa says `20190413.1246`, confirmed by looking at the latest commit in [openscad/openscad/contrib](https://github.com/openscad/openscad/tree/master/contrib)) but [emacsmirror/scad-mode](https://github.com/emacsmirror/scad-mode) seems to lag behind.

For curiosity I tried to give a look at the datbase but it seems to be correct:
```bash
sqlite3 epkg.sqlite -line "select * from packages where name like '%scad-mode%'"
...
              url = "git@github.com:openscad/openscad.git"
       mirror_url = "git@github.com:emacsmirror/scad-mode.git"
...
    upstream_tree = "contrib"
...
          updated = "20190413"
...
```

Feel free to close this issue if this isn't the right place to ask.

**Comment by tarsius** [comment]
I think what happened is that public history was rewritten. Normally I would notice that eventually, but it appears that filtered packages get stuck without any sign that something is wrong.

Thanks for letting me know!
