### ISSUE TITLE
Add the later-do package

### ISSUE THREAD

**Issue by anquegi** [emacsmirror/.github#8]
I thingk that later-do.el package should be available in emacsmirror, [https://www.emacswiki.org/emacs/later-do.el](https://www.emacswiki.org/emacs/later-do.el), is on the emacs wiki, but I could-t find on emacsmirror.

It is also cited in [wiki](https://www.emacswiki.org/emacs/ConcurrentEmacs), and I do not find anywhere, there seems that ale later version in [github_1](https://github.com/jasonchenscu/emacs/blob/093e0ed8297f0ffd63506471b22075798d473df2/emms/later-do.el) or [githuub_2](https://github.com/emacsattic)

**Comment by tarsius** [comment]
I am trying to have no feature conflicts in any mirrored packages. Considering how may packages there are we are doing pretty good: https://www.emacsmirror.net/stats/issues.html.

`do-later` and `emms` both have the same author. The former is a tiny, not particularly noteworthy helper library while the latter is a significant package. So we have to mirror the latter and cannot mirror the former in its own right. The fact that the bundled version is more recent than the stand-alone one also indicates that the author does not (anymore?) consider `do-later` as a package that is worth distributing in its own right.

If you care a lot about being able to use `do-later` without having to install `emms`, then I suggest that ask the author to move (not copy) it to a separate git repository, add it as a separate package to Melpa, and add it as a dependency of `emms`.

Not sure why `do-later` is available from the Emacsattic. It is not available in the Emacsmirror database (which contains information about the packages in the attic also). Probably an error occured when I was trying to remove the package. I am removing it manually now.
